version: '3.7'
services:
  animal-service:
    container_name: animal-service
    build:
      context: ../
      dockerfile: src/main/docker/Containerfile.temurin
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 128M
        reservations:
          cpus: 1
          memory: 128M
    env_file:
      - animal-service/.env
    ports:
      - '8080:8080'
      - '9999:9999'
    networks:
      - default
  # postgres + pgadmin4 web UI
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine3.17
    deploy:
      resources:
        limits:
          cpus: 4.0
    volumes:
      - ${REMOTE_PROJECT_PATH:-.}/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_DATABASES: animals
    ports:
      - "5432:5432"
    networks:
      - default
      - database
    tmpfs:
      - /var/lib/postgresql/data
  # pgadmin4 web UI - to interact with the postgres databases
  pgadmin4:
    profiles:
      - develop
    image: dpage/pgadmin4:6.21
    volumes:
      - ${REMOTE_LOCALDEPLOYMENT_DIR:-.}/pgadmin4/pgadmin4/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - postgres
    ports:
      - "60080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    networks:
      - database
networks:
  default:
    driver: bridge
  database:
    driver: bridge